### ISSUE TITLE
README initial environment instructions no longer valid

### ISSUE THREAD

**Issue by john-aws** [soap117/DeepRule#17]
The README suggests creating a conda environment as follows:

```
conda create  --DeepRule python-course --file DeepRule.txt
```

but this fails on recent conda installations (e.g. 4.10.3) with:

```
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --DeepRule
```

At a guess, this should now be:

```
conda create  --name DeepRule --file DeepRule.txt
```

**Comment by john-aws** [comment]
Also, the subsequent environment activation step should potentially change from:

```
source activate DeepRule
```

to the following:

```
conda activate DeepRule
```

**Comment by soap117** [comment]
Thanks for the update
