### ISSUE TITLE
The training is not progressing

### ISSUE THREAD

**Issue by Dong-gri-dong** [soap117/DeepRule#26]
The training is not progressing.

Please tell me how to solve it in detail... plz

![image](https://user-images.githubusercontent.com/29161866/193793312-bc2cd9a0-718b-4aff-aeaa-bc12b551c36f.png)

**Comment by shalinie22** [comment]
> The training is not progressing.
> 
> Please tell me how to solve it in detail... plz
> 
> ![image](https://user-images.githubusercontent.com/29161866/193793312-bc2cd9a0-718b-4aff-aeaa-bc12b551c36f.png)

Hi @sdh5349 ,

   How did you resolve this issue?
   Could you please explain?
