### ISSUE TITLE
Conda Package Not Exist

### ISSUE THREAD

**Issue by ydai94** [soap117/DeepRule#31]
The URL for the following two packages seemed not to work anymore when I tried to create the conda environment, they generated HTTP 404 error. I couldn't find similar packages on the Anaconda website, as the versions are quite old.

Could you please provide alternative URLs compatible with other packages in this project? Thank you very much!

https://conda.anaconda.org/pytorch/linux-64/pytorch-1.1.0-py3.6_cuda10.0.130_cudnn7.5.1_0.tar.bz2
https://conda.anaconda.org/pytorch/noarch/torchvision-0.2.1-py_2.tar.bz2

**Comment by AdeZwart** [comment]
I have the same issue and I'm unable to get the project up and running. Please provide updated dependencies.

**Comment by soap117** [comment]
I have add the new environment file see updates and is able to complie cpools layers

**Comment by AdeZwart** [comment]
The `requirements-2023.txt` file results in the following error:
```
CondaValueError: could not parse 'contourpy @ file:///opt/conda/conda-bld/contourpy_1663827406301/work' in: requirements-2023.txt
```
When I look at the file it contains a lot of those local file references.
